version: '3'
services:
  node-app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        VARIANT: 14

  mysql:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:cached
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports:
      - 6379:6379
    command: ["redis-server"]

volumes:
  db-store:
